---
name: Build Pacman Repo

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-pacman-repo:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    env:
      DISPLAY: ":1"
    steps:
      - name: Container Setup
        run: |
          pacman -Syu --disable-download-timeout --needed --noconfirm \
            archlinux-keyring \
            git \
            reflector \
            wget \
            xorg-server-xvfb

      - name: Update mirrors
        run: |
          reflector --latest 10 --protocol http,https --sort rate --save /etc/pacman.d/mirrorlist

      - name: Download Pacman Repo Builder
        env:
          VERSION: "0.0.0-rc.65"
          URL_ASSET: "build-pacman-repo-x86_64-unknown-linux-gnu"
        run: |
          wget \
            "https://github.com/pacman-repo-builder/pacman-repo-builder/releases/download/${VERSION}/${URL_ASSET}" \
            -O /usr/bin/build-pacman-repo
          chmod +x /usr/bin/build-pacman-repo

      - name: Checkout
        uses: actions/checkout@v4

      - name: Init
        run: |
          mkdir -p repo
          Xvfb ${DISPLAY} -screen 0 1024x768x24 &

      - name: Build Pacman Repo
        run: |
          build-pacman-repo patch-makepkg --replace
          build-pacman-repo build

      - name: Create/Update GitHub Release
        if: github.event_name == 'schedule' || github.event_name == 'push'
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: repo/*
          bodyFile: README.md
          commit: master
          name: repo
          prerelease: false
          tag: repo
          token: ${{ secrets.GH_BOT_TOKEN }}
